Architecture/Controllers/Admin/AdminController.cs
using Architecture.Services;
using Architecture.ViewModels.Category;
using Architecture.ViewModels.Product;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Architecture.Mvc.Controllers.Admin
{
    [Authorize]
    [Produces("application/json")]
    [Route("admin")]
    public class AdminController : Controller
    {
        private readonly ICategoryService _categoryService;
        private readonly IProductService _productService;

        public AdminController(
            ICategoryService categoryService,
            IProductService productService
        )
        {
            _categoryService = categoryService;
            _productService = productService;
        }

        [Route("")]
        public IActionResult Index()
        {
            return View();
        }

        [Route("categories")]
        public IActionResult ListCategories()
        {
            var model = new ListCategoriesViewModel()
            {
                Categories =
                    _categoryService
                        .GetAllCategoriesBase()
            };
            return View(model);
        }

        [Route("products")]
        public IActionResult ListProducts()
        {
            var model = new ListProductsViewModel()
            {
                Products =
                    _productService
                        .GetAllProductsBase()
            };
            return View(model);
        }
    }
}

Architecture/Controllers/Admin/ProductAdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Architecture.Models;
using Architecture.Services;
using Architecture.ViewModels.Product;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace Architecture.Mvc.Controllers.Admin
{
    [Authorize]
    [Produces("application/json")]
    [Route("admin/products")]
    public class ProductAdminController : Controller
    {
        private readonly IBrandService _brandService;
        private readonly ICategoryService _categoryService;
        private readonly IProductService _productService;
        private readonly IRatingService _ratingService;

        public ProductAdminController(
            IBrandService brandService,
            ICategoryService categoryService,
            IProductService productService,
            IRatingService ratingService
        )
        {
            _brandService = brandService;
            _categoryService = categoryService;
            _productService = productService;
            _ratingService = ratingService;
        }

        [HttpPost]
        [Route("search")]
        public IActionResult Search(ListProductsViewModel model)
        {
            if(!ModelState.IsValid || String.IsNullOrEmpty(model.SearchText))
            {
                model.Products =
                    _productService
                        .GetAllProductsBase();
                return View("ListProducts", model);
            }

            model.Products =
                    _productService
                        .SearchProductsBase(model.SearchText);

            return View("ListProducts", model);
        }

        [HttpGet]
        [Route("{id}/update")]
        public IActionResult Update(int id)
        {
            var product =
                _productService
                    .GetProductFull(id);
            if (product == null)
                return NotFound();

            var model = new UpdateProductViewModel()
            {
                Name = product.Name,
                Description = product.Description,
                Price = product.Price
            };

            _PopulateBrands(model, product.Brand.Id.ToString());
            _PopulateCategories(
                model,
                product
                    .Categories
                    .Select(x => x.Id.ToString())
            );
            _PopulateRatings(model, product.Id);

            return View(model);
        }

        [HttpPost]
        [Route("{id}/update")]
        public async Task<IActionResult> Update(int id, UpdateProductViewModel model)
        {
            if (ModelState.IsValid)
            {
                var product =
                    new ProductBase()
                    {
                        Id = id,
                        Name = model.Name,
                        Description = model.Description,
                        Price = model.Price
                    };

                var selectedCategoriesIds =
                    model
                        .SelectedCategories?
                        .Select(x => int.Parse(x)) ?? new int[0];
                var selectedBrandId =
                    int.Parse(
                        model
                            .SelectedBrand
                    );
                if (await TryUpdateModelAsync(product))
                {
                    _productService
                        .UpdateProductBase(product, selectedBrandId, selectedCategoriesIds);
                    return RedirectToAction("ListProducts", "Admin", null);
                }
                
            }
            _PopulateBrands(model);
            _PopulateCategories(model);
            _PopulateRatings(model);
            return View(model);
        }

        [HttpGet]
        [Route("create")]
        public IActionResult Create()
        {
            var model = new CreateProductViewModel();
            _PopulateBrands(model);
            _PopulateCategories(model);
            return View(model);
        }

        [HttpPost]
        [Route("create")]
        public IActionResult Create(CreateProductViewModel model)
        {
            if (ModelState.IsValid)
            {
                var selectedCategoriesIds =
                    model
                        .SelectedCategories?
                        .Select(x => int.Parse(x)) ?? new int[0];

                var selectedBrandId =
                    int.Parse(
                        model
                            .SelectedBrand
                    );

                _productService
                    .AddProduct(model.Name, model.Description, model.Price, selectedBrandId, selectedCategoriesIds);
                return RedirectToAction("ListProducts", "Admin", null);
            }
            _PopulateBrands(model, model.SelectedBrand);
            _PopulateCategories(model, model.SelectedCategories);
            return View();
        }

        [HttpGet]
        [Route("{id}/delete")]
        public IActionResult Delete(int id)
        {
            _productService
                .Delete(id);
            return RedirectToAction("ListProducts", "Admin", null);
        }

        private void _PopulateBrands(GenericEditProductViewModel model, string selectedBrand = null)
        {
            model.BrandsList =
                _brandService
                    .GetAllBrandsBase()
                    .Select(x => new SelectListItem
                    {
                        Text = x.Name,
                        Value = x.Id.ToString()
                    });

            model.SelectedBrand = selectedBrand;
        }

        private void _PopulateCategories(GenericEditProductViewModel model, IEnumerable<string> selectedCategories = null)
        {
            model.CategoriesList =
                _categoryService
                    .GetAllCategoriesBase()
                    .Select(x => new SelectListItem
                    {
                        Text = x.Title,
                        Value = x.Id.ToString()
                    });

            model.SelectedCategories = selectedCategories;
        }

        private void _PopulateRatings(GenericEditProductViewModel model, int productId = -1)
        {
            if(productId != -1)
                model.RatingsList =
                    _ratingService
                        .GetRatingsBaseByProduct(productId);
        }
    }
}

Architecture/Controllers/ProductFrontController.cs
using Architecture.Services;
using Architecture.ViewModels.Product;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Architecture.Mvc.Controllers
{
    [Route("products")]
    public class ProductFrontController : Controller
    {
        private readonly IProductService _productService;

        public ProductFrontController(
            IProductService productService
        )
        {
            _productService = productService;
        }

        [Route("{id}")]
        public IActionResult Read(int id)
        {
            var product =
                _productService
                    .GetProductFull(id);
            if (product == null)
                return NotFound();

            var model = new ShowProductViewModel()
            {
                Id = product.Id,
                Brand = product.Brand,
                Categories = product.Categories,
                Description = product.Description,
                Price = product.Price,
                Name = product.Name,
                Ratings = product.Ratings
            };

            return View(model);
        }

        [Authorize]
        [Route("{id}/tocart")]
        public IActionResult AddToCart(int id)
        {
            _productService
                .AddToCart(id, User);
            return RedirectToAction("Read", new { id });
        }
    }
}

Architecture/Views/Shared/ListProducts.cshtml
@{
    ViewData["Title"] = "Prodotti";
}
@model ListProductsViewModel

<div class="row">
    <h2>Modifica Prodotti</h2>
</div>
<hr />
<div class="row">
    <a asp-controller="ProductAdmin" asp-action="Create" class="btn btn-success">
        Aggiungi prodotto
    </a>
    <div class="pull-right">
        <form method="post" asp-controller="ProductAdmin" asp-action="Search">
            <div class="form-group">
                <input type="text" asp-for="@Model.SearchText" class="form-control" placeholder="Cerca.." />
                <br />
                <span asp-validation-for="@Model.SearchText"></span>
            </div>
            
        </form>
    </div>
</div>
<hr />
<div class="row">
    <table class="table table-striped table-bordered">
        <tr>
            <th></th>
            <th>Title</th>
            <th>Prezzo</th>
            <th></th>
        </tr>
        @foreach(var product in Model.Products)
        {
            <tr>
                <td>@product.Id</td>
                <td>@product.Name</td>
                <td>@product.Price</td>
                <td>
                    <a class="btn btn-xs btn-info" asp-controller="ProductAdmin" asp-action="Update" asp-route-id="@product.Id">Modifica</a>
                    <a class="btn btn-xs btn-primary" asp-controller="ProductFront" asp-action="Read" asp-route-id="@product.Id">Visualizza</a>
                    <a class="btn btn-xs btn-danger" asp-controller="ProductAdmin" asp-action="Delete" asp-route-id="@product.Id">Cancella</a>
                </td>
            </tr>

        }
    </table>
</div>

Architecture/Views/Shared/_AddToCart.cshtml
@using Microsoft.AspNetCore.Identity
@using Architecture.Database.Entities

@inject SignInManager<User> SignInManager
@inject UserManager<User> UserManager

@if (SignInManager.IsSignedIn(User))
{
    <div class="row">
        <a asp-action="AddToCart" asp-controller="ProductFront" class="btn btn-primary">Aggiungi al carrello</a>
    </div>
}

Architecture/Views/Shared/_EditCategory.cshtml
@model GenericEditCategoryViewModel

<div class="form-group">
    <label>
        Titolo:
    </label>
    <input type="text" asp-for="@Model.Title" class="form-control" />
    <br />
    <span asp-validation-for="@Model.Title"></span>
</div>

Architecture/Views/Shared/_EditProduct.cshtml
@model GenericEditProductViewModel

<div class="form-group">
    <label>Nome:</label>
    <br />
    <input type="text" asp-for="@Model.Name" class="form-control" />
    <br />
    <span class="alert-danger" asp-validation-for="@Model.Name"></span>
</div>
<div class="form-group">
    <label>Descrizione</label>
    <br />
    <textarea asp-for="@Model.Description" class="form-control"></textarea>
    <br />
    <span class="alert-danger" asp-validation-for="@Model.Description"></span>
</div>
<div class="form-group">
    <label>Prezzo</label>
    <br />
    <input type="text" asp-for="@Model.Price" class="form-control" />
    <br />
    <span class="alert-danger" asp-validation-for="@Model.Price"></span>
</div>
<div class="form-group">
    <label>Brand</label>
    <br />
    <select asp-for="@Model.SelectedBrand" asp-items="@Model.BrandsList" class="form-control"></select>
</div>
<div class="form-group">
    <label>Categorie</label>
    <br />
    <select asp-for="@Model.SelectedCategories" asp-items="@Model.CategoriesList" class="form-control"></select>
</div>

Architecture/Views/Shared/_Layout.cshtml
@inject Microsoft.ApplicationInsights.AspNetCore.JavaScriptSnippet JavaScriptSnippet
@inject IStringLocalizer Localizer
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - @Localizer["Say hi"]</title>

    <environment names="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/lib/bootswatch/superhero/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/lib/bootswatch/superhero/bootstrap.min.css" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
    @Html.Raw(JavaScriptSnippet.FullScript)
</head>
<body>
    <nav class="navbar navbar-default navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">Architecture</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">@Localizer["Home"]</a></li>
                    <li><a asp-area="" asp-controller="Admin" asp-action="Index">@Localizer["Admin"]</a></li>
                </ul>
                @await Html.PartialAsync("_LoginPartial")
            </div>
        </div>
    </nav>
    <environment names="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment names="Staging,Production">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2017 - Architecture</p>
        </footer>
    </div>

    

    @RenderSection("Scripts", required: false)
</body>
</html>

Architecture/Views/Shared/_ListAdminRatings.cshtml
@model IEnumerable<Architecture.Models.RatingBase>

<div class="row">
    <h3>Cancella votazioni</h3>
    <hr />
    <div class="col-md-offset-2 col-md-8">
        <table class="table table-striped table-bordered">
            <tr>
                <th></th>
                <th>Votazione</th>
                <th>Commento</th>
                <th>Utente</th>
                <th></th>
            </tr>
            @foreach (var rating in Model)
            {
                <tr>
                    <td>@rating.Id</td>
                    <td>@rating.Vote</td>
                    <td>@rating.Comment</td>
                    <td>@rating.User.UserName</td>
                    <td>
                        <button class="btn btn-xs btn-danger delete-rating" data-rating-id="@rating.Id">Cancella</button>
                    </td>
                </tr>
            }
        </table>
    </div>
</div>

<script>
    $(document)
        .ready(function () {
            $('.delete-rating')
                .bind('click', function (e) {
                    var element = this;
                    var ratingId = $(element).attr('data-rating-id');
                    $.ajax({
                        url: "/api/ratings/" + ratingId + "/",
                        method: "DELETE",
                        success: () => {
                            $(element)
                                .parent('tr')
                                .remove();
                        }
                    })
                });
        });
</script>

Architecture/Views/Shared/_ProductThumbnail.cshtml
@model ProductBase

<div class="col-md-4 col-xs-6">
    <div class="panel panel-primary">
        <div class="panel-heading">
            @Model.Name
        </div>
        <div class="panel-body">
            <p>
                @Model.Name
            </p>
            <p>
                @String.Format("{0:C}", Model.Price)
            </p>
        </div>
    </div>
</div>