Architecture/Controllers/Admin/CategoryAdminController.cs
using System.Threading.Tasks;
using Architecture.Models;
using Architecture.Services;
using Architecture.ViewModels.Category;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Architecture.Mvc.Controllers.Admin
{
    [Authorize]
    [Route("admin/categories")]
    public class CategoryAdminController : Controller
    {
        private readonly ICategoryService _categoryService;

        public CategoryAdminController(
            ICategoryService categoryService
        )
        {
            _categoryService = categoryService;
        }

        [HttpGet]
        [Route("create")]
        public IActionResult Create()
        {
            var model = new CreateCategoryViewModel()
            {
                Title = ""
            };
            return View(model);
        }

        [HttpPost]
        [Route("create")]
        public IActionResult Create(CreateCategoryViewModel model)
        {
            if (!ModelState.IsValid)
                return View(model);
            _categoryService
                .AddCategory(model.Title);
            return RedirectToAction("ListCategories", "Admin", null);
        }
        
        [HttpGet]
        [Route("{id}/update")]
        public IActionResult Update(int id)
        {
            var category =
                _categoryService
                    .GetCategoryBase(id);

            if (category == null)
                return NotFound();

            var model = new UpdateCategoryViewModel()
            {
                Title = category.Title
            };

            return View(model);
        }

        [HttpPost]
        [Route("{id}/update")]
        public async Task<IActionResult> Update(int id, UpdateCategoryViewModel model)
        {
            if (!ModelState.IsValid)
                return View(model);
            var category = new CategoryBase()
            {
                Id = id,
                Title = model.Title
            };
            if (!await TryUpdateModelAsync(category))
                return View(model);
            _categoryService
                .UpdateCategoryBase(category);
            return RedirectToAction("ListCategories", "Admin", null);
        }

        [HttpGet]
        [Route("{id}/delete")]
        public IActionResult Delete(int id)
        {
            _categoryService
                .Delete(id);
            return RedirectToAction("ListCategories", "Admin", null);
        }
    }
}

Architecture/Controllers/Admin/LocalizationAdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Architecture.Application.Services;
using Architecture.ViewModels.Account.Manage;
using Architecture.ViewModels.Controllers;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Architecture.Mvc.Controllers.Admin
{
    [Authorize]
    [Route("admin/localizations")]
    public class LocalizationAdminController : Controller
    {
        private readonly IAdminLocalizationControllerService _service;

        public LocalizationAdminController(
            IAdminLocalizationControllerService service
        )
        {
            _service = service;
        }

        [Route("")]
        public IActionResult Index()
        {
            return View(_service.GetIndexViewModel());
        }

        [HttpPost]
        [Route("create")]
        public IActionResult Create(AdminLocalizationIndexViewModel model)
        {
            if (ModelState.IsValid)
            {
                _service.AddLocalization(model);
                return RedirectToAction("Index");
            }
            return View(_service.GetIndexViewModel(model));
        }

        [HttpGet]
        [Route("delete")]
        public IActionResult Delete(string culture, string key)
        {
            _service
                .Delete(culture, key);
            return RedirectToAction("Index");
        }
    }
}

Architecture/Views/Admin/Index.cshtml
@{
    ViewData["Title"] = "Admin";
}

@inject IStringLocalizer Localizer

<h2>
    @Localizer["Admin Panel"]
</h2>
<hr />
<div class="row">
    <div class="col-md-offset-1 col-sm-offset-1 col-xs-offset-1">
        <a class="btn btn-info" style="margin: 5px 0px;" asp-action="ListCategories" asp-controller="Admin">
            @Localizer["Update Categories"]
        </a>
        <a class="btn btn-info" style="margin: 5px 0px;" asp-action="ListProducts" asp-controller="Admin">
            @Localizer["Update Products"]
        </a>
        <a class="btn btn-info disabled" style="margin: 5px 0px;">
            @Localizer["Update Brands"]
        </a>
        <a class="btn btn-info" style="margin: 5px 0px;" asp-action="Index" asp-controller="LocalizationAdmin">
            @Localizer["Update Localization"]
        </a>
    </div>
    
</div>

Architecture/Views/Admin/ListCategories.cshtml
@{
    ViewData["Title"] = "Categorie";
}
@model ListCategoriesViewModel

<div class="row">
    <h2>Modifica categorie</h2>
</div>
<hr />
<div class="row">
    <a asp-controller="CategoryAdmin" asp-action="Create" class="btn btn-success">
        Aggiungi categoria
    </a>
</div>
<hr />
<div class="row">
    <table class="table table-striped table-bordered">
        <tr>
            <th></th>
            <th>Title</th>
            <th></th>
        </tr>
        @foreach(var category in Model.Categories)
        {
            <tr>
                <td>@category.Id</td>
                <td>@category.Title</td>
                <td>
                    <a class="btn btn-xs btn-info" asp-controller="CategoryAdmin" asp-action="Update" asp-route-id="@category.Id">Modifica</a>
                    <a class="btn btn-xs btn-danger" asp-controller="CategoryAdmin" asp-action="Delete" asp-route-id="@category.Id">Cancella</a>
                </td>
            </tr>

        }
    </table>
</div>